### ISSUE TITLE
Question about this dataset

### ISSUE THREAD

**Issue by ray007330** [aws-samples/machine-learning-pipelines-for-multimodal-health-data#1]
Hi,

I use this dataset(NSCLC) for my model training and I encounter a problem that I don't know how to deal the .xml annotation file. The coordinates of roi seems weird that I can't just use python tools to extract them. Could you help about this problem? Thanks.

**Comment by michaelhsieh42** [comment]
Hi we don't use .xml files in this work. Please reach out to the dataset owner listed in https://wiki.cancerimagingarchive.net/display/Public/NSCLC+Radiogenomics for this question. Thanks.
